name: Feature Request
description: Suggest a new idea or improvement for Citron
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: Describe your idea in detail.
      placeholder: What would you like to see added or changed?
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Why should this be added?
      description: How does this improve Citron? (e.g., better performance, better visuals)
      placeholder: Explain the benefit to the users...
    validations:
      required: true

  - type: dropdown
    id: branch
    attributes:
      label: Applicable Branch
      description: Which version of Citron would this feature benefit?
      options:
        - Citron Core
        - Citron Leaf
        - Both
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Details
      description: Include links to mod pages, screenshots, or specific configuration ideas.
      placeholder: Any extra information...
